apiVersion: v2
appVersion: 1.29-alpha.1441efaff68abda7aa2dbf62fee7da7f4537b8cc
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

