apiVersion: v2
appVersion: 1.29-alpha.fdc9f373bd86be0ea81b1d0fd68cae44a272d1d4
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

