apiVersion: v2
appVersion: 1.30-alpha.7847ff0952b1ae22ee209b5499b10c623d0c7b6f
description: Helm chart for deploying Istio cluster resources and CRDs
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
name: base
sources:
- https://github.com/istio/istio
version: 1.30-alpha.7847ff0952b1ae22ee209b5499b10c623d0c7b6f
