apiVersion: v2
appVersion: 1.29-alpha.1cbc5c7fcaa0ab22df1914f1bca23033940d5e36
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

