apiVersion: v2
appVersion: 1.30-alpha.2c4ef39afcdee1515729cd8b16b30ea6ec62078c
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

