apiVersion: v2
appVersion: 1.30-alpha.1389e271c97279124d66a8798af0011f52c2be58
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

