apiVersion: v2
appVersion: 1.28-alpha.6000d6f4713c022c017f95d2ab8f54aa10b620e3
description: Helm chart for deploying Istio gateways
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
- gateways
name: gateway
sources:
- https://github.com/istio/istio
type: application
version: 1.28-alpha.6000d6f4713c022c017f95d2ab8f54aa10b620e3
