apiVersion: v2
appVersion: 1.30-alpha.a3b3111f47165267e876b4236dc8acf7ee98ce3a
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

