apiVersion: v2
appVersion: 1.30-alpha.bbb2b88526a4210b45bef191cc653dc9374e1ed8
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

