apiVersion: v2
appVersion: 1.30-alpha.07f0c3780a5eeca968a2cb81a445c8d1a09ddadb
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

