apiVersion: v2
appVersion: 1.29-alpha.166562a05528e7adadbde78a77ba1d418f9b796c
description: Helm chart for deploying Istio gateways
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
- gateways
name: gateway
sources:
- https://github.com/istio/istio
type: application
version: 1.29-alpha.166562a05528e7adadbde78a77ba1d418f9b796c
