apiVersion: v2
appVersion: 1.30-alpha.8a7ac6f6b06cd450a7338db8f88463d9adb1e75f
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

