apiVersion: v2
appVersion: 1.30-alpha.0a3466091a333998e160a8aa3400a3aa65d4cb7a
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

