apiVersion: v2
appVersion: 1.29-alpha.d52e82173d52b03663278a89d22193c5976f5fd9
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

