apiVersion: v2
appVersion: 1.29-alpha.f2fd76afb4c6a3b9adb64df7c3763b52d7114325
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

