apiVersion: v2
appVersion: 1.30-alpha.bb3ecf92885c4d626a548466186d8947866c1c25
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

