apiVersion: v2
appVersion: 1.30-alpha.4d7a765cf81a69e8c1a3e38b5f64c5fc1bc64360
description: Helm chart for istio-cni components
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio-cni
- istio
name: cni
sources:
- https://github.com/istio/istio
version: 1.30-alpha.4d7a765cf81a69e8c1a3e38b5f64c5fc1bc64360
