apiVersion: v2
appVersion: 1.30-alpha.cdc5dca45da0afcf59f428f90093b4b4ab51c907
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

