apiVersion: v2
appVersion: 1.30-alpha.eed996de8e84d7a3cd62417214e27b38300efdfa
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

