apiVersion: v2
appVersion: 1.30-alpha.4746acec474d7a2a1b32f75aa71bebbfcf855c9a
description: Helm chart for istio ztunnel components
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio-ztunnel
- istio
name: ztunnel
sources:
- https://github.com/istio/istio
version: 1.30-alpha.4746acec474d7a2a1b32f75aa71bebbfcf855c9a
