apiVersion: v2
appVersion: 1.29-alpha.9960f64e259f7c238e149473829c4045a5e9f8df
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

