apiVersion: v2
appVersion: 1.29-alpha.166562a05528e7adadbde78a77ba1d418f9b796c
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

