apiVersion: v2
appVersion: 1.29-alpha.2abdd2f54c2ee52fdef5645a32ddb009ceeb51b7
description: Helm chart for deploying Istio gateways
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
- gateways
name: gateway
sources:
- https://github.com/istio/istio
type: application
version: 1.29-alpha.2abdd2f54c2ee52fdef5645a32ddb009ceeb51b7
