apiVersion: v2
appVersion: 1.29-alpha.277f6ecc7d13a8d45e92b1ff20957e3c64e0b48e
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

