apiVersion: v2
appVersion: 1.29-alpha.d4ef8b2a081b31f76581b88add1ddd3a3d79006f
description: Helm chart for deploying Istio cluster resources and CRDs
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
name: base
sources:
- https://github.com/istio/istio
version: 1.29-alpha.d4ef8b2a081b31f76581b88add1ddd3a3d79006f
