apiVersion: v2
appVersion: 1.30-alpha.58342d620ee2c08a3e60684c1175fe36e96bef02
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

