apiVersion: v2
appVersion: 1.30-alpha.37de52d1fc7bce4b22b43a886b4d3ba35981da77
description: Helm chart for istio-cni components
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio-cni
- istio
name: cni
sources:
- https://github.com/istio/istio
version: 1.30-alpha.37de52d1fc7bce4b22b43a886b4d3ba35981da77
