apiVersion: v2
appVersion: 1.30-alpha.0997af56bba72e58bb3d64a28d8bcc7657001451
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

