apiVersion: v2
appVersion: 1.30-alpha.eab5fb0686458842f328ff53f0d985ec1fa6df5e
description: Helm chart for istio-cni components
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio-cni
- istio
name: cni
sources:
- https://github.com/istio/istio
version: 1.30-alpha.eab5fb0686458842f328ff53f0d985ec1fa6df5e
