apiVersion: v2
appVersion: 1.29-alpha.33f915853bfb34aeadeb59496e70972d99144eb7
description: Helm chart for istio ztunnel components
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio-ztunnel
- istio
name: ztunnel
sources:
- https://github.com/istio/istio
version: 1.29-alpha.33f915853bfb34aeadeb59496e70972d99144eb7
