apiVersion: v2
appVersion: 1.29-alpha.2abdd2f54c2ee52fdef5645a32ddb009ceeb51b7
description: Helm chart for istio-cni components
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio-cni
- istio
name: cni
sources:
- https://github.com/istio/istio
version: 1.29-alpha.2abdd2f54c2ee52fdef5645a32ddb009ceeb51b7
