apiVersion: v2
appVersion: 1.29-alpha.c24fe2aebd9b6330f180bbc9fcf81ee431e5a460
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

