apiVersion: v2
appVersion: 1.30-alpha.b38ad9e43536da97f4c7f0259d7a313aa17b69b3
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

