apiVersion: v2
appVersion: 1.29-alpha.d8f0973a0a13d7f07879407bf19fdb2fe6756940
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

