apiVersion: v2
appVersion: 1.30-alpha.ed0ec1b7f434bafb88b3a6b1ae7e204e2704cab8
description: Helm chart for deploying Istio cluster resources and CRDs
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
name: base
sources:
- https://github.com/istio/istio
version: 1.30-alpha.ed0ec1b7f434bafb88b3a6b1ae7e204e2704cab8
