apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: gateway-controller
spec:
  version: v1.28.3
  namespace: gateway-controller
  updateStrategy:
    type: InPlace
    inactiveRevisionDeletionGracePeriodSeconds: 30
  values:
    pilot:
      resources:
        requests:
          cpu: 100m
          memory: 1024Mi
