apiVersion: v2
appVersion: 1.30-alpha.cdc5dca45da0afcf59f428f90093b4b4ab51c907
description: Helm chart for istio ztunnel components
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio-ztunnel
- istio
name: ztunnel
sources:
- https://github.com/istio/istio
version: 1.30-alpha.cdc5dca45da0afcf59f428f90093b4b4ab51c907
