apiVersion: v2
appVersion: 1.30-alpha.3c9f2b4b7e0885d2e67258600966c5df4a852c0e
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

