apiVersion: v2
appVersion: 1.30-alpha.0f695af0187022e11b9f6f5cc6445e498814dafe
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

