apiVersion: v2
appVersion: 1.30-alpha.86fdbf972e0da72308e75da5352b9349e25e683a
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

