apiVersion: v2
appVersion: 1.30-alpha.a6c6f0b2386aebf9eb7000b9875fa104b1dc2c7f
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

