apiVersion: v2
appVersion: 1.30-alpha.6c76e33806da8172561dc39742a22c0ee0f221e8
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

