apiVersion: v2
appVersion: 1.29-alpha.33f915853bfb34aeadeb59496e70972d99144eb7
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

