apiVersion: v2
appVersion: 1.30-alpha.7847ff0952b1ae22ee209b5499b10c623d0c7b6f
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

