apiVersion: v2
appVersion: 1.30-alpha.3c78a9f2c76caf2b751054a3ae7ac086a10bae5d
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

