apiVersion: v2
appVersion: 1.30-alpha.37de52d1fc7bce4b22b43a886b4d3ba35981da77
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

