apiVersion: v2
appVersion: 1.29-alpha.3762c4fadbce6207eab9fe40f07cecc0078361ee
description: Helm chart for istio-cni components
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio-cni
- istio
name: cni
sources:
- https://github.com/istio/istio
version: 1.29-alpha.3762c4fadbce6207eab9fe40f07cecc0078361ee
