apiVersion: v2
appVersion: 1.30-alpha.6b64542698a31ee8f735d185ef733897cfd3c68b
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

