apiVersion: v2
appVersion: 1.29-alpha.2abdd2f54c2ee52fdef5645a32ddb009ceeb51b7
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

