apiVersion: v2
appVersion: 1.30-alpha.6c76e33806da8172561dc39742a22c0ee0f221e8
description: Helm chart for deploying Istio cluster resources and CRDs
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
name: base
sources:
- https://github.com/istio/istio
version: 1.30-alpha.6c76e33806da8172561dc39742a22c0ee0f221e8
