apiVersion: v2
appVersion: 1.30-alpha.51d9879758e665ab6be2f7077e526b77ce469cc2
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

