apiVersion: v2
appVersion: 1.30-alpha.941c7435d35fdebdea431237a8dc966bd0bbdd64
description: Helm chart for istio ztunnel components
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio-ztunnel
- istio
name: ztunnel
sources:
- https://github.com/istio/istio
version: 1.30-alpha.941c7435d35fdebdea431237a8dc966bd0bbdd64
