apiVersion: v2
appVersion: 1.30-alpha.15986c2fb5c9a42a8c5890c13e1ff7bf13020c2f
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

