apiVersion: v2
appVersion: 1.29-alpha.513e752759ef71a807115011c70de80fb3ad91c2
description: Helm chart for deploying Istio cluster resources and CRDs
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
name: base
sources:
- https://github.com/istio/istio
version: 1.29-alpha.513e752759ef71a807115011c70de80fb3ad91c2
