apiVersion: v2
appVersion: 1.30-alpha.3376ee0d0770559f0a88687c79510f3fc6677688
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

