apiVersion: v2
appVersion: 1.30-alpha.ec64c6713f2147b3530261d4bb5a57278bfe3c40
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

