apiVersion: v2
appVersion: 1.30-alpha.eab5fb0686458842f328ff53f0d985ec1fa6df5e
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

