apiVersion: v2
appVersion: 1.29-alpha.513e752759ef71a807115011c70de80fb3ad91c2
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

