apiVersion: v2
appVersion: 1.29-alpha.9aed894daba662948574e8b31f63e4a04baca3d2
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

