apiVersion: v2
appVersion: 1.29-alpha.e854c51909997092a9d97fda4952791e57ee1a6e
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

