apiVersion: v2
appVersion: 1.29-alpha.9960f64e259f7c238e149473829c4045a5e9f8df
description: Helm chart for deploying Istio gateways
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
- gateways
name: gateway
sources:
- https://github.com/istio/istio
type: application
version: 1.29-alpha.9960f64e259f7c238e149473829c4045a5e9f8df
