apiVersion: v2
appVersion: 1.29-alpha.9eb419397d4091303e3bb04a3f2c9f64f9d511e9
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

