apiVersion: v2
appVersion: 1.30-alpha.2c4ef39afcdee1515729cd8b16b30ea6ec62078c
description: Helm chart for deploying Istio cluster resources and CRDs
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
name: base
sources:
- https://github.com/istio/istio
version: 1.30-alpha.2c4ef39afcdee1515729cd8b16b30ea6ec62078c
