apiVersion: v2
appVersion: 1.30-alpha.0997af56bba72e58bb3d64a28d8bcc7657001451
description: Helm chart for deploying Istio cluster resources and CRDs
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
name: base
sources:
- https://github.com/istio/istio
version: 1.30-alpha.0997af56bba72e58bb3d64a28d8bcc7657001451
