apiVersion: v2
appVersion: 1.30-alpha.d5f36ab1545d47bec2ee4c97216c91dbfd34e42d
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

