apiVersion: v2
appVersion: 1.29-alpha.477a4e1ee6a4d0e4e10d4156c91d71e9169a1f2a
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

