apiVersion: v2
appVersion: 1.29-alpha.dcfb1b0b8e59f9c59ed989ed7bc5ca1967806d10
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

