apiVersion: v2
appVersion: 1.30-alpha.1389e271c97279124d66a8798af0011f52c2be58
description: Helm chart for istio-cni components
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio-cni
- istio
name: cni
sources:
- https://github.com/istio/istio
version: 1.30-alpha.1389e271c97279124d66a8798af0011f52c2be58
