apiVersion: v2
appVersion: 1.29-alpha.945ca92435b5c43332f37067d467e799ed8b50ab
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

