apiVersion: v2
appVersion: 1.30-alpha.4746acec474d7a2a1b32f75aa71bebbfcf855c9a
description: Helm chart for deploying Istio gateways
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
- gateways
name: gateway
sources:
- https://github.com/istio/istio
type: application
version: 1.30-alpha.4746acec474d7a2a1b32f75aa71bebbfcf855c9a
