name: Code coverage workflow

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run coverage
      run: |
        make test.unit \
          -e COVERAGE=true

    - name: Upload to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: out/coverage.out
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true