apiVersion: v2
appVersion: 1.29-alpha.84f506a5273e57c72e2c8b5ab99e5d007770d370
description: Helm chart for istio revision tags
name: revisiontags
sources:
- https://github.com/istio-ecosystem/sail-operator
version: 0.1.0

